### PR TITLE
Api WebApp CI/CD Pipelines

### PR DESCRIPTION
**Pull request by kirasoderstrom**
Manually:
- Ran web-resource-provisioning.yml to create web resources
- Created Variable group for inputs manually #TODO to create this in preprovisioning pipelines. The variable group contains web variables for CI/CD: "appServiceNameApi", "azureContainerRegistry", "azureSubscriptionEndpoint", "resourceGroupName"
- Added to Application Settings configuration the following values: "AzureDevOpsProjectName", "AzureDevOpsPipelineBuildId", "AzureDevOpsUri", and "AzureDevOpsPersonalAccessToken" (See below for example inputs, the pipeline that we are triggering is the network module currently)
- Created CI/CD pipelines from api-webapp-CI and api-webapp-CD
- Triggered CI and then CD pipelines

Application Settings Configuration example values (not shown is PAT) 
image

Our Api WebApp currently supports the triggering of the network pipeline. We run CI/CD to create a docker image and push to our ACR then grab the image and deploy to the web app.

image

Once the WebApp is deployed we go to swagger to kick off the networking pipeline from our WebApp.

image

image

We see that the network pipeline was successfully triggered and that we have the expected resources.

image

### CODE REVIEW

**Comment by timmyreilly** [comment]
Before we move forward with this feature can we add the required resources to the pre-provisioning terraform? So we don't have to manually create the variable group?

**Comment by timmyreilly** [comment]
How is the azure container registry deployed? I think we may want to consider writing this in it's own module.

**Comment by kirasoderstrom** [comment]
@timmyreilly the web resources including ACR is initialized through web-resource-provisioning.yml leveraging my web terraform. The docker images are being created, pushed to ACR, and deployed to the WebApp through these pipelines I am merging in.

**Comment by kirasoderstrom** [comment]
@timmyreilly I would prefer to get these pipelines merged in because they are stable and do work if the variable group is manually created. I can start working on the task to automatically initialize a variable group to support the automation of this additional resource. It is a little complicated because I have to update the terraform in both preprovioning and web because we need values from both pipelines 1. service connection name 2. web resources names.

**Pull request merged**
